server:
  port: 8085

spring:
  application:    name: config-server
  cloud:
    config:      server:
        git:
          default-label: main
          uri: https://github.com/anushaputta-git/spring-cloud-config-repo
      
      
    
  